spring.application.name=groww-sip-tracker

DRY_RUN=true
API_PROVIDER=breeze


EMAIL_FROM=your.email@gmail.com
EMAIL_TO=your.alerts@email.com
EMAIL_PASSWORD=your_app_password

ALERT_MODE=telegram/email


GROWW_API_TOKEN=your_token_here
GROWW_FUND_ID=your_fund_id_here

GROWW_API_KEY=
GROWW_API_SECRET=

TOTP_SECRET_SOURCE=file
TOTP_SECRET_FILE=secure/raw.secret
# TOTP_SECRET_SOURCE=vault
# TOTP_SECRET_VAULT_KEY=groww/totp

#ICICI
BREEZE_APP_KEY=
BREEZE_SECRET_KEY=


BOT_TOKEN=your_telegram_bot_token
CHAT_ID=your_telegram_chat_id

LOG_DIR=logs
ENCRYPTION_KEY=your-32-byte-base64-key
